<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sam</string>
		<string>saminfo</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{:? *(##.*)?$</string>
	<key>foldingStopMarker</key>
	<string>^[^\{]*\} *(##.*)?$</string>
	<key>name</key>
	<string>Samizdat</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#block-body</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#recursive-comment</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.preprocessor.samizdat</string>
					<key>match</key>
					<string>#=.*$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>comment.line.number-sign.samizdat</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.samizdat</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.samizdat</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(#!|###*).*$</string>
				</dict>
			</array>
		</dict>
		<key>recursive-comment</key>
		<dict>
			<key>name</key>
			<string>comment.block.samizdat</string>
			<key>begin</key>
			<string>#:</string>
			<key>end</key>
			<string>:#</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#recursive-comment</string>
				</dict>
			</array>
		</dict>
		<key>recursive-string-content</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.samizdat</string>
					<key>match</key>
					<string>\\ *$</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.character.escape.samizdat</string>
					<key>match</key>
					<string>(?x)
						\\
						(
						  [0nrt\\"/]
						|
						  x[0-9a-fA-F_,]*;?
						|
						  &amp;[0-9a-zA-Z.,]*;?
						)
					</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.interpolated.samizdat</string>
					<key>begin</key>
					<string>\\(%[0-9a-zA-Z+-.]*)?[\[({]</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.samizdat string.quoted.double.samizdat</string>
						</dict>
					</dict>
					<key>end</key>
					<string>[\])}]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.samizdat string.quoted.double.samizdat</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block-body</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>recursive-string</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.samizdat string.quoted.double.samizdat</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.samizdat string.quoted.double.samizdat</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#recursive-string-content</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.quoted.double.samizdat</string>
					<key>match</key>
					<string>.</string>
				</dict>
			</array>
		</dict>
		<key>identifier-symbol</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.unquoted.samizdat</string>
					<key>match</key>
					<string>[_$a-zA-Z][_$a-zA-Z0-9]*</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#recursive-string</string>
				</dict>
			</array>
		</dict>
		<key>import-list</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.definition.samizdat</string>
					<key>match</key>
					<string>[_$a-zA-Z0-9]+\*?(?= *[=,;])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.unquoted.samizdat</string>
					<key>match</key>
					<string>\./[./_$a-zA-Z0-9]*</string>
				</dict>
				<dict>
					<key>name</key>
					<string>string.unquoted.samizdat</string>
					<key>match</key>
					<string>[./_$a-zA-Z0-9]+</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.other.samizdat</string>
					<key>match</key>
					<string>@[_$a-zA-Z0-9]+</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.samizdat</string>
					<key>match</key>
					<string>=</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.samizdat</string>
					<key>match</key>
					<string>::</string>
				</dict>
			</array>
		</dict>
		<key>simple-constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#recursive-string</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.samizdat</string>
					<key>match</key>
					<string>-?\b[0-9_]+\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.samizdat</string>
					<key>match</key>
					<string>\b0x-?[0-9a-fA-F_]+\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.samizdat</string>
					<key>match</key>
					<string>(?x)\[\] | @?\{\}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric.samizdat</string>
					<key>match</key>
					<string>\b0b-?[01_]+\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.other.samizdat</string>
					<key>match</key>
					<string>@\.?[_$a-zA-Z][_$a-zA-Z0-9]*</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.other.samizdat</string>
					<key>begin</key>
					<string>@\.?"</string>
					<key>end</key>
					<string>"</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#recursive-string-content</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>block-body</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#simple-constants</string>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.parens.samizdat</string>
					<key>begin</key>
					<string>@(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.other.samizdat</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.paren.open.samizdat</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>constant.other.samizdat punctuation.paren.close.samizdat</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block-body</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.parens.samizdat</string>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.paren.open.samizdat</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.paren.close.samizdat</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block-body</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.collection.samizdat</string>
					<key>begin</key>
					<string>\[</string>
					<key>end</key>
					<string>\]</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.bracket.open.samizdat</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.bracket.close.samizdat</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block-body</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.block.parser.samizdat</string>
					<key>begin</key>
					<string>\{:</string>
					<key>end</key>
					<string>:\}</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parser.begin.samizdat</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.parser.end.samizdat</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block-body</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>meta.block.samizdat</string>
					<key>begin</key>
					<string>@?\{</string>
					<key>end</key>
					<string>\}</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.brace.open.samizdat</string>
						</dict>
					</dict>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.brace.close.samizdat</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#block-body</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.other.samizdat</string>
					<key>begin</key>
					<string>\\"</string>
					<key>end</key>
					<string>"</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#recursive-string-content</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.samizdat</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.binding.samizdat</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([_$a-zA-Z][_$a-zA-Z0-9]*) *(:)(?![:=])</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.samizdat</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.definition.samizdat</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(def|var)  *([_$a-zA-Z][_$a-zA-Z0-9]*)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.samizdat</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.samizdat</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(yield\??)  *(/[_$a-zA-Z][_$a-zA-Z0-9]*)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.samizdat</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.definition.samizdat</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(if|do|for|switch|while)  *(/[_$a-zA-Z][_$a-zA-Z0-9]*)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.definition.samizdat</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.samizdat</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([_$a-zA-Z][_$a-zA-Z0-9]*) *(:?=)(?!=)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.samizdat</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.function.samizdat</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([_$a-zA-Z./][^:@"{}()\[\]]*) *(-&gt;)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>meta.function.samizdat</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.definition.samizdat</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.samizdat</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.samizdat</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x)
						(?:(?&lt;=\ )|^)   (?# lookbehind is spc or bol )
						(fn\b|\.|class\.)
						\ *
						(\*?\.?@*[_$a-zA-Z][._$a-zA-Z0-9]*)?
						\ *
						\(([^\(\)"]*)\)
					</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(::) *</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.samizdat</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=[^"_$a-zA-Z0-9])</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#identifier-symbol</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>import(?=[^_$a-zA-Z0-9])</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.control.import.samizdat</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#import-list</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.import.samizdat</string>
					<key>match</key>
					<string>\bimport\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.export.samizdat</string>
					<key>match</key>
					<string>\bexport\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.control.samizdat</string>
					<key>match</key>
					<string>(?x)
						\b(break|continue|return|yield)\b\??
						|
						\b(default|do|else|for|if|switch|while)\b
					</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.definition.samizdat</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.class.samizdat</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(class)  *([_$a-zA-Z][_$a-zA-Z0-9]*)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.definition.samizdat</string>
					<key>match</key>
					<string>(?x)
						\b(by|def|fn|in|module|var)\b
					</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.samizdat</string>
					<key>match</key>
					<string>(?x)
						\b(as|isa)\b
					</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.language.samizdat</string>
					<key>match</key>
					<string>(?x)
						\b(true|false|null|nullBox|nullGenerator|voidResult)\b
					</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.function-call.samizdat</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([._$a-zA-Z][._$a-zA-Z0-9:]*)\b(?= *[({])</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.other.samizdat</string>
					<key>match</key>
					<string>[_$a-zA-Z][_$a-zA-Z0-9]*</string>
				</dict>
				<dict>
					<key>name</key>
					<string>variable.other.dot-access.samizdat</string>
					<key>match</key>
					<string>\.[_$a-zA-Z][_$a-zA-Z0-9]*</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parser.begin.samizdat</string>
					<key>match</key>
					<string>\{:</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parser.end.samizdat</string>
					<key>match</key>
					<string>:\}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.brace.open.samizdat</string>
					<key>match</key>
					<string>\{</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.brace.close.samizdat</string>
					<key>match</key>
					<string>\}</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.bracket.open.samizdat</string>
					<key>match</key>
					<string>\[</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.bracket.close.samizdat</string>
					<key>match</key>
					<string>\]</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.paren.open.samizdat</string>
					<key>match</key>
					<string>\(</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.paren.close.samizdat</string>
					<key>match</key>
					<string>\)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.definition.binding.samizdat</string>
					<key>match</key>
					<string>:</string>
				</dict>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.samizdat</string>
					<key>match</key>
					<string>-&gt;</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator.samizdat</string>
					<key>match</key>
					<string>(?x)
						&amp;&amp;?&amp;? | \|\|?\|? | \^\^?\^? |
						\\?&lt;&lt;?&lt;? | \\?&gt;&gt;?&gt;? | !!?!? |
						:[:=] | \\?[!&lt;&gt;]?==? |
						\.\.!? | \+ | - | \* | //? | %%? | \? | \#
					</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.samizdat</string>
	<key>uuid</key>
	<string>ACB22210-E84C-11E2-91E2-0800200C9A66</string>
</dict>
</plist>
